---
- name: Create directory
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
  with_items:
    - "sites-available"
    - "sites-enabled"

- name: Copy nginx's config file
  template:
    src=nginx.conf.j2 dest="{{nginx_conf_dir}}/nginx.conf"
  notify:
    - restart nginx

- name: Create the configurations for sites
  copy:
    src: "files/{{ item }}"
    dest: "{{ nginx_conf_dir }}/sites-available/{{ item }}.conf"
  with_list: "{{ nginx_sites }}"
  notify:
    - restart nginx

- name: Create links for sites-enabled
  file:
    state: link
    src: "{{ nginx_conf_dir }}/sites-available/{{ item }}.conf"
    dest: "{{ nginx_conf_dir }}/sites-enabled/{{ item }}.conf"
  with_list: "{{ nginx_sites }}"
  notify:
    - restart nginx
