---
# tasks file for ansible-role-nginx
- include_tasks: centos6.yml
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version == '6'"

- include_tasks: tell_user_platform_is_not_supported.yml
